import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { marked } from 'marked'

const SITE_URL = process.env.SITE_URL ?? 'https://abdooay.github.io/ai-news-digest'
const SITE_TITLE = 'AI News Digest'
const SITE_TAGLINE = 'Plain-language digests of official Anthropic and OpenAI announcements, written by a scheduled Claude agent.'

const POSTS_DIR = 'posts'
const OUT_DIR = 'dist'

function parsePost(raw, file) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/)
  if (!m) throw new Error(`${file}: missing front-matter block`)
  const meta = {}
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':')
    if (i === -1) continue
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim()
  }
  for (const k of ['title', 'date', 'description']) {
    if (!meta[k]) throw new Error(`${file}: missing required front-matter key "${k}"`)
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(meta.date)) throw new Error(`${file}: date must be YYYY-MM-DD`)
  return { ...meta, body: m[2], slug: file.replace(/\.md$/, '') }
}

function escapeHtml(s) {
  return s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
}

const CSS = `
:root { color-scheme: light dark; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  max-width: 42rem; margin: 0 auto; padding: 2rem 1.25rem 4rem;
  line-height: 1.65; color: #1a1a1a; background: #fdfdfc;
}
@media (prefers-color-scheme: dark) {
  body { color: #d9d9d6; background: #161614; }
  a { color: #8ab4f8; }
  header.site a, .meta { color: #8a8a86; }
  code, pre { background: #24241f; }
}
a { color: #0b57d0; text-decoration: none; }
a:hover { text-decoration: underline; }
header.site { margin-bottom: 2.5rem; }
header.site h1 { margin: 0 0 0.25rem; font-size: 1.4rem; }
header.site p, .meta { margin: 0; color: #6b6b68; font-size: 0.9rem; }
article.summary { margin-bottom: 2rem; }
article.summary h2 { margin: 0 0 0.2rem; font-size: 1.1rem; }
main h1 { font-size: 1.6rem; line-height: 1.3; }
code, pre { background: #f0f0ec; border-radius: 4px; }
code { padding: 0.1em 0.35em; font-size: 0.9em; }
pre { padding: 0.9rem; overflow-x: auto; }
pre code { padding: 0; background: none; }
blockquote { margin: 0; padding-left: 1rem; border-left: 3px solid #ccc; }
footer.site { margin-top: 3rem; font-size: 0.85rem; }
`

function shell({ title, homeHref, content }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<link rel="alternate" type="application/rss+xml" title="${escapeHtml(SITE_TITLE)}" href="${homeHref}feed.xml">
<style>${CSS}</style>
</head>
<body>
<header class="site">
<h1><a href="${homeHref}">${escapeHtml(SITE_TITLE)}</a></h1>
<p>${escapeHtml(SITE_TAGLINE)}</p>
</header>
<main>
${content}
</main>
<footer class="site meta"><a href="${homeHref}feed.xml">RSS</a> · generated by a scheduled Claude agent; sources linked in every post</footer>
</body>
</html>
`
}

rmSync(OUT_DIR, { recursive: true, force: true })
mkdirSync(OUT_DIR, { recursive: true })

const posts = readdirSync(POSTS_DIR)
  .filter((f) => f.endsWith('.md'))
  .map((f) => parsePost(readFileSync(join(POSTS_DIR, f), 'utf8'), f))
  .sort((a, b) => (a.date === b.date ? b.slug.localeCompare(a.slug) : b.date.localeCompare(a.date)))

for (const post of posts) {
  const dir = join(OUT_DIR, 'posts', post.slug)
  mkdirSync(dir, { recursive: true })
  const content = `<article>
<h1>${escapeHtml(post.title)}</h1>
<p class="meta">${post.date}</p>
${marked.parse(post.body)}
</article>`
  writeFileSync(join(dir, 'index.html'), shell({ title: `${post.title} — ${SITE_TITLE}`, homeHref: '../../', content }))
}

const index = posts
  .map(
    (p) => `<article class="summary">
<h2><a href="posts/${p.slug}/">${escapeHtml(p.title)}</a></h2>
<p class="meta">${p.date}</p>
<p>${escapeHtml(p.description)}</p>
</article>`
  )
  .join('\n')
writeFileSync(join(OUT_DIR, 'index.html'), shell({ title: SITE_TITLE, homeHref: './', content: index || '<p>No posts yet.</p>' }))

const rssItems = posts
  .slice(0, 20)
  .map(
    (p) => `<item>
<title>${escapeHtml(p.title)}</title>
<link>${SITE_URL}/posts/${p.slug}/</link>
<guid>${SITE_URL}/posts/${p.slug}/</guid>
<pubDate>${new Date(`${p.date}T09:00:00Z`).toUTCString()}</pubDate>
<description>${escapeHtml(p.description)}</description>
</item>`
  )
  .join('\n')
writeFileSync(
  join(OUT_DIR, 'feed.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>${escapeHtml(SITE_TITLE)}</title>
<link>${SITE_URL}/</link>
<description>${escapeHtml(SITE_TAGLINE)}</description>
${rssItems}
</channel>
</rss>
`
)

console.log(`built ${posts.length} post(s) -> ${OUT_DIR}/`)
